n = input('Digite algo:')
print('Qual o tipo?', type(n))
print('Só tem espaço?', n.isspace())
print('É um numérico?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Está em minúsculo?', n.islower())
print('Está em maiúsculo?', n.isupper())